CREATE DATABASE BARD&RODGE;

-- Employees Table
CREATE TABLE EMPLOYEES (
    E_ID INT PRIMARY KEY AUTO_INCREMENT,
    E_REGNUMBER VARCHAR(255) UNIQUE NOT NULL,
    FIRSTNAME VARCHAR(150),
    LASTNAME VARCHAR(150),
    E_ROLE VARCHAR(50),
    E_PHONE VARCHAR(20),
    E_IDNUMBER VARCHAR(20),
    E_STATUS ENUM('1', '0') DEFAULT '1'
 -- Add other relevant columns
);

-- Users Table
CREATE TABLE USERS (
    U_ID INT PRIMARY KEY AUTO_INCREMENT,
    E_ID INT,
    U_NAME VARCHAR(50),
    U_PASSWORD VARCHAR(255),
    U_STATUS ENUM('1', '0') DEFAULT '1',
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEES(E_ID),
 -- Add other relevant columns
);

CREATE TABLE SESSIONS (
    S_ID VARCHAR(255) PRIMARY KEY,
    ACTIONDESCRIPTION VARCHAR(255),
    DATEOCCURRED DATETIME,
    E_ID INT,
 -- Add other relevant columns
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEES(E_ID)
);

-- Metric Table
CREATE TABLE METRIC (
    M_ID INT PRIMARY KEY AUTO_INCREMENT,
    E_ID INT NOT NULL,
    S_ID VARCHAR(255) NULL,
    M_DESC VARCHAR(255),
    DATE_OCCURRED DATE,
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEES(E_ID),
    FOREIGN KEY (S_ID) REFERENCES SESSION(S_ID)
 -- Add other relevant columns
);

-- Product_Type Table
CREATE TABLE PRODUCT_TYPE (
    PT_ID INT PRIMARY KEY AUTO_INCREMENT,
    PT_NAME VARCHAR(50),
 -- Add other relevant columns
);

-- Product_Category Table
CREATE TABLE PRODUCT_CATEGORY (
    PC_ID INT PRIMARY KEY AUTO_INCREMENT,
    PT_ID INT,
    PC_NAME VARCHAR(50),
    FOREIGN KEY (PT_ID) REFERENCES PRODUCT_TYPE(PT_ID),
 -- Add other relevant columns
);